name: 'Read Metronome Meters'
author: 'Konstantin Kudryashov (everzet)'
description: 'Reads meters and updates their readings stored in a repository'

branding:
  icon: 'thermometer'
  color: 'blue'

runs:
  using: 'node12'
  main: 'dist/index.js'

inputs:
  commit-token:
    description: 'A GitHub token, which would be used to commit readings file'
    required: true
  commit-branch:
    description: 'A branch to commit readings to'
    required: true
    default: 'master'
  readings-env:
    description: 'Environment name that meters are tracking'
    required: true
    default: 'prod'
  readings-path:
    description: 'File to commit meter readings into'
    required: true
    default: 'kpis/latest.${readings-env}.json'
  meters-script:
    description: 'A script exporting all repository meters'
    required: true
    default: 'kpis/meters/index.js'

outputs:
  readings:
    description: 'Current meter readings'
