const TOML = require("@iarna/toml");

module.exports = (readings) =>
  prependAutogenerationNote(TOML.stringify(orderMapProperties(readings)));

function orderMapProperties(unordered) {
  const ordered = {};

  Object.keys(unordered)
    .sort()
    .forEach((key) => {
      ordered[key] = unordered[key];
    });

  return ordered;
}

function prependAutogenerationNote(text) {
  return `# FILE IS AUTOGENERATED

${text}`;
}
