name: Test Metronome CLI

on:
  push:
    branches: [ master ]
    paths:
    - '.github/workflows/test-metronome-cli.yml'
    - 'metronome-cli/**'

  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/test-metronome-cli.yml'
    - 'metronome-cli/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '12', '14' ]

    defaults:
      run:
        working-directory: 'metronome-cli'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache NPM modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
